plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-plugin-tracing
  - serverless-prune-plugin
  - serverless-aws-documentation

service: wallets
custom:
  pythonRequirements:
    fileName: wallets/requirements.txt
    dockerizePip: true
    useDownloadCache: true
    useStaticCache: true
    cacheLocation: '/var/cache/serverless'
  prune:
    automatic: true
    includeLayers: true
    number: 2
  documentation:
    models:
      - name: "ErrorMessage"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/error.json)}
      - name: "PostWalletOutput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/post_wallet.json):PostWalletOutput}
      - name: "PostWalletInput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/post_wallet.json):PostWalletInput}
      - name: "GetWalletOutput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/get_wallet.json):GetWalletOutput}
      - name: "WalletRegisterOutput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/wallet_register.json):WalletRegisterOutput}
      - name: "WalletRegisterInput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/wallet_register.json):WalletRegisterInput}
      - name: "WalletChannelDepositOutput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/wallet_channel_deposit.json):WalletChannelDepositOutput}
      - name: "WalletChannelDepositInput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/wallet_channel_deposit.json):WalletChannelDepositInput}
      - name: "WalletStatusOutput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/wallet_status.json):WalletStatusOutput}
      - name: "WalletStatusInput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/wallet_status.json):WalletStatusInput}
      - name: "WalletTransactionsOutput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/wallet_transactions.json):WalletTransactionsOutput}
      - name: "CreateChannelOutput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/create_channel.json):CreateChannelOutput}
      - name: "CreateChannelInput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/create_channel.json):CreateChannelInput}
      - name: "DeleteUserWalletOutput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/delete_user_wallet.json):DeleteUserWalletOutput}
      - name: "DeleteUserWalletInput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/delete_user_wallet.json):DeleteUserWalletInput}
      - name: "CreateChannelEventOutput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/create_channel_event.json):CreateChannelEventOutput}
      - name: "CreateChannelEventInput"
        contentType: "application/json"
        schema: ${file(wallets/documentation/models/create_channel_event.json):CreateChannelEventInput}

provider:
  name: aws
  runtime: python3.7
  description: Dapp user service# optional, Description to publish to AWS
  memorySize: 128
  timeout: 30
  region: ${file(./config.${self:provider.stage}.json):REGION}
  stage: ${opt:stage,'dev'}
  deploymentBucket:
    name: snet-serverless-artifacts # Deployment bucket name. Default is generated by the framework
    serverSideEncryption: AES256 # when using server-side encryption
    tags: # Tags that will be added to each of the deployment resources
      key1: wallets
  deploymentPrefix: serverless
  versionFunctions: false
  tracing: true

package:
  exclude:
    - .circleci/**
    - .gitignore/**
    - .serverless/**
    - requirements.txt
    - venv/**
    - config.ropsten.json
    - test/**
    - testcase/**
    - sql_script/**
    - service_status/**
    - contract_api/**
    - dapp-user/**
    - payments/**
    - repository/**
    - Readme.md
    - parse_events.sh
    - package.json
    - Dockerfile
    - License
    - log_setup.py
    - heath_check.sh

functions:
  wallets:
    warmup: true
    handler: wallets/lambda_handler.request_handler
    role: ${file(./config.${self:provider.stage}.json):ROLE}
    tags:
      Environment: ${file(./config.${self:provider.stage}.json):ENVIRONMENT}
      Team: ${file(./config.${self:provider.stage}.json):TEAM}
      Owner: ${file(./config.${self:provider.stage}.json):OWNER}
    vpc:
      securityGroupIds:
        - ${file(./config.${self:provider.stage}.json):SG1}
        - ${file(./config.${self:provider.stage}.json):SG2}
      subnetIds:
        - ${file(./config.${self:provider.stage}.json):VPC1}
        - ${file(./config.${self:provider.stage}.json):VPC2}
    events:
      - http:
          method: POST
          path: /wallet
          private: true
          authorizer:
            name: user-authorizer
            type: COGNITO_USER_POOLS
            arn: ${file(./config.${self:provider.stage}.json):AUTHORIZER}
            identitySource: method.request.header.Authorization
          documentation:
            summary: "Get wallet"
            description: "Get Wallet"
            tags:
              - "wallet"
            requestHeaders:
              - name: "Content-Type"
                description: "application/json"
            requestModels:
              "application/json": "PostWalletInput"
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "response"
                responseModels:
                  "application/json": "PostWalletOutput"
              - statusCode: "500"
                responseModels:
                  "application/json": "ErrorMessage"

      - http:
          method: GET
          path: /wallet
          private: true
          documentation:
            summary: "Get wallet"
            description: "Get Wallet"
            tags:
              - "wallet"
            requestHeaders:
              - name: "Content-Type"
                description: "application/json"
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "response"
                responseModels:
                  "application/json": "GetWalletOutput"
              - statusCode: "500"
                responseModels:
                  "application/json": "ErrorMessage"
      - http:
          method: POST
          path: /wallet/register
          private: true
          authorizer:
            name: user-authorizer
            type: COGNITO_USER_POOLS
            arn: ${file(./config.${self:provider.stage}.json):AUTHORIZER}
            identitySource: method.request.header.Authorization
          documentation:
            summary: "Register Wallet"
            description: "Register Wallet"
            tags:
              - "wallet"
            requestHeaders:
              - name: "Content-Type"
                description: "application/json"
            requestModels:
              "application/json": "WalletRegisterInput"
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "response"
                responseModels:
                  "application/json": "WalletRegisterOutput"
              - statusCode: "500"
                responseModels:
                  "application/json": "ErrorMessage"
      - http:
          method: POST
          path: /wallet/channel/deposit
          private: true
          authorizer:
            name: user-authorizer
            type: COGNITO_USER_POOLS
            arn: ${file(./config.${self:provider.stage}.json):AUTHORIZER}
            identitySource: method.request.header.Authorization
          documentation:
            summary: "Deposit to channel"
            description: "Deposit to channel wallet"
            tags:
              - "wallet"
            requestHeaders:
              - name: "Content-Type"
                description: "application/json"
            requestModels:
              "application/json": "WalletChannelDepositInput"
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "response"
                responseModels:
                  "application/json": "WalletChannelDepositOutput"
              - statusCode: "500"
                responseModels:
                  "application/json": "ErrorMessage"
      - http:
          method: POST
          path: /wallet/status
          private: true
          authorizer:
            name: user-authorizer
            type: COGNITO_USER_POOLS
            arn: ${file(./config.${self:provider.stage}.json):AUTHORIZER}
            identitySource: method.request.header.Authorization
          documentation:
            summary: "Get wallet status"
            description: "Get wallet status"
            tags:
              - "wallet"
            requestHeaders:
              - name: "Content-Type"
                description: "application/json"
            requestModels:
              "application/json": "WalletStatusInput"
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "response"
                responseModels:
                  "application/json": "WalletStatusOutput"
              - statusCode: "500"
                responseModels:
                  "application/json": "ErrorMessage"

      - http:
          method: GET
          path: /wallet/transactions
          private: true
          authorizer:
            name: user-authorizer
            type: COGNITO_USER_POOLS
            arn: ${file(./config.${self:provider.stage}.json):AUTHORIZER}
            identitySource: method.request.header.Authorization
          documentation:
            summary: "Get wallet transactions"
            description: "Get wallet transactions"
            tags:
              - "wallet"
            requestHeaders:
              - name: "Content-Type"
                description: "application/json"
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "response"
                responseModels:
                  "application/json": "WalletTransactionsOutput"
              - statusCode: "500"
                responseModels:
                  "application/json": "ErrorMessage"

  create-channel:
    warmup: true
    handler: wallets/handlers/channel_handler.create_channel
    role: ${file(./config.${self:provider.stage}.json):ROLE}
    vpc:
      securityGroupIds:
        - ${file(./config.${self:provider.stage}.json):SG1}
        - ${file(./config.${self:provider.stage}.json):SG2}
      subnetIds:
        - ${file(./config.${self:provider.stage}.json):VPC1}
        - ${file(./config.${self:provider.stage}.json):VPC2}
    events:
      - http:
          method: POST
          path: /wallet/channel
          private: true
          authorizer:
            name: user-authorizer
            type: COGNITO_USER_POOLS
            arn: ${file(./config.${self:provider.stage}.json):AUTHORIZER}
            identitySource: method.request.header.Authorization
          documentation:
            summary: "Create channel"
            description: "Create channel"
            tags:
              - "wallet"
            requestHeaders:
              - name: "Content-Type"
                description: "application/json"
            requestModels:
              "application/json": "CreateChannelInput"
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "response"
                responseModels:
                  "application/json": "CreateChannelOutput"
              - statusCode: "500"
                responseModels:
                  "application/json": "ErrorMessage"


  delete-user-wallet:
    warmup: true
    handler: wallets/handlers/wallet_handlers.delete_user_wallet
    role: ${file(./config.${self:provider.stage}.json):ROLE}
    vpc:
      securityGroupIds:
        - ${file(./config.${self:provider.stage}.json):SG1}
        - ${file(./config.${self:provider.stage}.json):SG2}
      subnetIds:
        - ${file(./config.${self:provider.stage}.json):VPC1}
        - ${file(./config.${self:provider.stage}.json):VPC2}
    events:
      - http:
          method: POST
          path: /wallet/delete
          private: true
          documentation:
            summary: "Delete user wallet"
            description: "Delete user wallet"
            tags:
              - "wallet"
            requestHeaders:
              - name: "Content-Type"
                description: "application/json"
            requestModels:
              "application/json": "DeleteUserWalletInput"
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "response"
                responseModels:
                  "application/json": "DeleteUserWalletOutput"
              - statusCode: "500"
                responseModels:
                  "application/json": "ErrorMessage"

  create-channel-event:
    warmup: true
    handler: wallets/handlers/channel_handler.record_create_channel_event
    role: ${file(./config.${self:provider.stage}.json):ROLE}
    vpc:
      securityGroupIds:
        - ${file(./config.${self:provider.stage}.json):SG1}
        - ${file(./config.${self:provider.stage}.json):SG2}
      subnetIds:
        - ${file(./config.${self:provider.stage}.json):VPC1}
        - ${file(./config.${self:provider.stage}.json):VPC2}
    events:
      - http:
          method: POST
          path: /wallet/channel/event
          private: true
          documentation:
            summary: "Create channel event"
            description: "Create channel event "
            tags:
              - "channel"
            requestHeaders:
              - name: "Content-Type"
                description: "application/json"
            requestModels:
              "application/json": "CreateChannelEventInput"
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "response"
                responseModels:
                  "application/json": "CreateChannelEventOutput"
              - statusCode: "500"
                responseModels:
                  "application/json": "ErrorMessage"

  channelTxnStatus:
    warmup: true
    handler: wallets/handlers/channel_transaction_status_handler.request_handler
    role: ${file(./config.${self:provider.stage}.json):ROLE}
    vpc:
      securityGroupIds:
        - ${file(./config.${self:provider.stage}.json):SG1}
        - ${file(./config.${self:provider.stage}.json):SG2}
      subnetIds:
        - ${file(./config.${self:provider.stage}.json):VPC1}
        - ${file(./config.${self:provider.stage}.json):VPC2}
    events:
      - schedule: rate(2 minutes)

  open-channel-by-third-party:
    handler: wallets/handlers/channel_handler.open_channel_by_third_party
    role: ${file(./config.${self:provider.stage}.json):ROLE}
    vpc:
      securityGroupIds:
        - ${file(./config.${self:provider.stage}.json):SG1}
        - ${file(./config.${self:provider.stage}.json):SG2}
      subnetIds:
        - ${file(./config.${self:provider.stage}.json):VPC1}
        - ${file(./config.${self:provider.stage}.json):VPC2}
    events:
      - schedule: rate(2 minutes)
