"""free_call_token

Revision ID: 441dbc36f043
Revises: 
Create Date: 2025-06-05 11:01:52.698875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '441dbc36f043'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('free_call_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('organization_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('service_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('group_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('token', sa.VARBINARY(length=512), nullable=False),
    sa.Column('expiration_block_number', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_token_body', 'free_call_token', ['username', 'organization_id', 'service_id', 'group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_body', table_name='free_call_token')
    op.drop_table('free_call_token')
    # ### end Alembic commands ###
