"""converter_cgv

Revision ID: 01bebb82d45a
Revises: aa569e5e1ad5
Create Date: 2023-05-30 15:07:10.925844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01bebb82d45a'
down_revision = 'aa569e5e1ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('converter_cgv_events_raw',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('uncle_block_no', sa.Integer(), nullable=True),
    sa.Column('event', sa.VARCHAR(length=256), nullable=False),
    sa.Column('json_str', sa.VARCHAR(length=256), nullable=True),
    sa.Column('processed', mysql.BIT(), nullable=True),
    sa.Column('transactionHash', sa.VARCHAR(length=256), nullable=True),
    sa.Column('logIndex', sa.VARCHAR(length=256), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.VARCHAR(length=256), nullable=True),
    sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True),
    sa.Column('row_created', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('transactionHash', name='uq_converter_cgv_ev')
    )
    op.create_index('blk_no_idx', 'converter_cgv_events_raw', ['block_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('blk_no_idx', table_name='converter_cgv_events_raw')
    op.drop_table('converter_cgv_events_raw')
    # ### end Alembic commands ###
