"""converter-ntx

Revision ID: 632dd0534d07
Revises: 33e4423afef6
Create Date: 2022-03-14 11:34:52.045770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '632dd0534d07'
down_revision = '33e4423afef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('converter_ntx_events_raw',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('uncle_block_no', sa.Integer(), nullable=True),
    sa.Column('event', sa.VARCHAR(length=256), nullable=False),
    sa.Column('json_str', sa.VARCHAR(length=256), nullable=True),
    sa.Column('processed', mysql.BIT(), nullable=True),
    sa.Column('transactionHash', sa.VARCHAR(length=256), nullable=True),
    sa.Column('logIndex', sa.VARCHAR(length=256), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.VARCHAR(length=256), nullable=True),
    sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True),
    sa.Column('row_created', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('transactionHash', 'logIndex', name='uq_converter_ntx_ev')
    )
    op.create_index('blk_no_idx', 'converter_ntx_events_raw', ['block_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('blk_no_idx', table_name='converter_ntx_events_raw')
    op.drop_table('converter_ntx_events_raw')
    # ### end Alembic commands ###
