"""converter-rjv

Revision ID: aa569e5e1ad5
Revises: c43c9dd9a19f
Create Date: 2023-03-17 15:34:45.935579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa569e5e1ad5'
down_revision = 'c43c9dd9a19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('converter_rjv_events_raw',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('uncle_block_no', sa.Integer(), nullable=True),
    sa.Column('event', sa.VARCHAR(length=256), nullable=False),
    sa.Column('json_str', sa.VARCHAR(length=256), nullable=True),
    sa.Column('processed', mysql.BIT(), nullable=True),
    sa.Column('transactionHash', sa.VARCHAR(length=256), nullable=True),
    sa.Column('logIndex', sa.VARCHAR(length=256), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.VARCHAR(length=256), nullable=True),
    sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True),
    sa.Column('row_created', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('transactionHash', name='uq_converter_rjv_ev')
    )
    op.create_index('blk_no_idx', 'converter_rjv_events_raw', ['block_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('blk_no_idx', table_name='converter_rjv_events_raw')
    op.drop_table('converter_rjv_events_raw')
    # ### end Alembic commands ###
