"""UpdateUniqueContraintOnAirdropEventsRaw

Revision ID: ab2543ca5262
Revises: c3185e288b60
Create Date: 2021-10-26 13:49:50.465450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2543ca5262'
down_revision = 'c3185e288b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_airdrop_ev', table_name='airdrop_events_raw')
    op.create_unique_constraint('uq_txnhash_logindex', 'airdrop_events_raw', ['transactionHash', 'logIndex'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_txnhash_logindex', 'airdrop_events_raw', type_='unique')
    op.create_index('uq_airdrop_ev', 'airdrop_events_raw', ['transactionHash'], unique=True)
    # ### end Alembic commands ###
