"""AirdropEventsTable

Revision ID: c3185e288b60
Revises: b84618836559
Create Date: 2021-10-22 10:52:54.409313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3185e288b60'
down_revision = 'b84618836559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airdrop_events_raw',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('uncle_block_no', sa.Integer(), nullable=True),
    sa.Column('event', sa.VARCHAR(length=256), nullable=False),
    sa.Column('json_str', sa.VARCHAR(length=256), nullable=True),
    sa.Column('processed', mysql.BIT(), nullable=True),
    sa.Column('transactionHash', sa.VARCHAR(length=256), nullable=True),
    sa.Column('logIndex', sa.VARCHAR(length=256), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.VARCHAR(length=256), nullable=True),
    sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True),
    sa.Column('row_created', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('transactionHash', name='uq_airdrop_ev')
    )
    op.create_index('blk_no_idx', 'airdrop_events_raw', ['block_no'], unique=False)
    op.drop_constraint('uq_st_ev', 'token_stake_events_raw', type_='unique')
    op.create_unique_constraint('uq_st_ev', 'token_stake_events_raw', ['transactionHash', 'logIndex'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_st_ev', 'token_stake_events_raw', type_='unique')
    op.create_unique_constraint('uq_st_ev', 'token_stake_events_raw', ['transactionHash'])
    op.drop_index('blk_no_idx', table_name='airdrop_events_raw')
    op.drop_table('airdrop_events_raw')
    # ### end Alembic commands ###
