"""remove logindex for unique constraint

Revision ID: c43c9dd9a19f
Revises: 632dd0534d07
Create Date: 2022-04-19 22:00:57.017561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43c9dd9a19f'
down_revision = '632dd0534d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_converter_agix_ev', 'converter_agix_events_raw', type_='unique')
    op.create_unique_constraint('uq_converter_agix_ev', 'converter_agix_events_raw', ['transactionHash'])
    op.drop_constraint('uq_converter_ntx_ev', 'converter_ntx_events_raw', type_='unique')
    op.create_unique_constraint('uq_converter_ntx_ev', 'converter_ntx_events_raw', ['transactionHash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_converter_ntx_ev', 'converter_ntx_events_raw', type_='unique')
    op.create_unique_constraint('uq_converter_ntx_ev', 'converter_ntx_events_raw', ['transactionHash', 'logIndex'])
    op.drop_constraint('uq_converter_agix_ev', 'converter_agix_events_raw', type_='unique')
    op.create_unique_constraint('uq_converter_agix_ev', 'converter_agix_events_raw', ['transactionHash', 'logIndex'])
    # ### end Alembic commands ###
