"""baseline

Revision ID: e12dfc595535
Revises:
Create Date: 2025-06-23 13:02:44.493675

"""

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "e12dfc595535"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("row_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.VARCHAR(length=128), nullable=False),
        sa.Column("account_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("name", sa.VARCHAR(length=128), nullable=False),
        sa.Column("email", sa.VARCHAR(length=128), nullable=False),
        sa.Column("email_verified", sa.BOOLEAN(), nullable=False),
        sa.Column("email_alerts", sa.BOOLEAN(), nullable=False),
        sa.Column("status", sa.BOOLEAN(), nullable=False),
        sa.Column("request_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("request_time_epoch", sa.VARCHAR(length=128), nullable=False),
        sa.Column("is_terms_accepted", sa.BOOLEAN(), nullable=False),
        sa.Column(
            "created_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("row_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "user_preference",
        sa.Column("row_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_row_id", sa.BigInteger(), nullable=False),
        sa.Column("preference_type", sa.VARCHAR(length=128), nullable=False),
        sa.Column("communication_type", sa.VARCHAR(length=128), nullable=False),
        sa.Column("source", sa.VARCHAR(length=128), nullable=False),
        sa.Column("opt_out_reason", sa.VARCHAR(length=256), nullable=True),
        sa.Column("status", sa.BOOLEAN(), nullable=False),
        sa.Column(
            "created_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_row_id"], ["user.row_id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("row_id"),
        sa.UniqueConstraint(
            "user_row_id",
            "preference_type",
            "communication_type",
            "source",
            name="user_preference_unique",
        ),
    )
    op.create_table(
        "user_service_feedback",
        sa.Column("row_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_row_id", sa.BigInteger(), nullable=False),
        sa.Column("org_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("service_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("comment", sa.VARCHAR(length=1024), nullable=True),
        sa.Column(
            "row_created",
            mysql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "row_updated",
            mysql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_row_id"], ["user.row_id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("row_id"),
    )
    op.create_table(
        "user_service_vote",
        sa.Column("row_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_row_id", sa.BigInteger(), nullable=False),
        sa.Column("org_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("service_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("rating", sa.DECIMAL(precision=2, scale=1), nullable=True),
        sa.Column(
            "row_created",
            mysql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "row_updated",
            mysql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_row_id"], ["user.row_id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("row_id"),
        sa.UniqueConstraint("user_row_id", "org_id", "service_id", name="user_service_vote_unique"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_service_vote")
    op.drop_table("user_service_feedback")
    op.drop_table("user_preference")
    op.drop_table("user")
    # ### end Alembic commands ###
