"""baseline

Revision ID: e46dc1dce28b
Revises: 
Create Date: 2020-01-09 14:56:23.600767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e46dc1dce28b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    conn.execute("""
            CREATE TABLE `user` (
              `row_id` int(11) NOT NULL AUTO_INCREMENT,
              `username` varchar(128) NOT NULL,
              `account_id` varchar(128) NOT NULL,
              `origin` varchar(50) NULL DEFAULT NULL,
              `name` varchar(128) NOT NULL,
              `email` varchar(128) NOT NULL,
              `email_verified` bit(1) DEFAULT b'0',
              `email_alerts` bit(1) DEFAULT b'0',
              `status` bit(1) DEFAULT b'0',
              `request_id` varchar(128) NOT NULL,
              `request_time_epoch` varchar(128) NOT NULL,
              `is_terms_accepted` bit(1) DEFAULT b'0',
              `row_created` timestamp NULL DEFAULT NULL,
              `row_updated` timestamp NULL DEFAULT NULL,
              PRIMARY KEY (`row_id`),
              UNIQUE KEY `uq_usr` (`username`),
              UNIQUE KEY `uq_usr_email` (`email`)
            ) ;
       """)
    conn.execute("""
             CREATE TABLE `user_service_vote` (
              `row_id` int(11) NOT NULL AUTO_INCREMENT,
              `username` varchar(128) NOT NULL,
              `org_id` varchar(128) NOT NULL,
              `service_id` varchar(128) NOT NULL,
              `rating` float(2,1) DEFAULT NULL,
              `row_created` timestamp DEFAULT NULL,
              `row_updated` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
              PRIMARY KEY (`row_id`),
              UNIQUE KEY `unique_vote` (`username`,`org_id`,`service_id`)
            ) ;
    """)
    conn.execute("""
            CREATE TABLE `user_service_feedback` (
              `row_id` int(11) NOT NULL AUTO_INCREMENT,
              `username` varchar(128) NOT NULL,
              `org_id` varchar(128) NOT NULL,
              `service_id` varchar(128) NOT NULL,
              `comment` varchar(1024) DEFAULT NULL,
              `row_created` timestamp NULL DEFAULT NULL,
              `row_updated` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
              PRIMARY KEY (`row_id`)
            );
       """)
    op.create_table('user_preference',
        sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_row_id', sa.Integer(), nullable=False),
        sa.Column('preference_type', sa.VARCHAR(length=128), nullable=False),
        sa.Column('communication_type', sa.VARCHAR(length=128), nullable=False),
        sa.Column('source', sa.VARCHAR(length=128), nullable=False),
        sa.Column('opt_out_reason', sa.VARCHAR(length=256), nullable=True),
        sa.Column('status', sa.BOOLEAN(), nullable=False),
        sa.Column('created_on', mysql.TIMESTAMP(), nullable=False),
        sa.Column('updated_on', mysql.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(['user_row_id'], ['user.row_id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('row_id'),
        sa.UniqueConstraint('preference_type', 'communication_type', 'source', 'user_row_id', name='uq_usr_pref')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preference')
    op.drop_table('user_service_feedback')
    op.drop_table('user_service_vote')
    op.drop_table('user')
    # ### end Alembic commands ###
