"""baseline

Revision ID: e46dc1dce28b
Revises: 
Create Date: 2020-01-09 14:56:23.600767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e46dc1dce28b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_row_id', sa.Integer(), nullable=False),
    sa.Column('preference_type', sa.VARCHAR(length=128), nullable=False),
    sa.Column('communication_type', sa.VARCHAR(length=128), nullable=False),
    sa.Column('source', sa.VARCHAR(length=128), nullable=False),
    sa.Column('opt_out_reason', sa.VARCHAR(length=256), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('created_on', mysql.TIMESTAMP(), nullable=False),
    sa.Column('updated_on', mysql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_row_id'], ['user.row_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('preference_type', 'communication_type', 'source', name='uq_usr_pref')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preference')
    # ### end Alembic commands ###
