"""hosted_service_new_status

Revision ID: 5c8704c9b2b7
Revises: b08498266523
Create Date: 2026-02-12 17:07:29.480331

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c8704c9b2b7"
down_revision: Union[str, None] = "b08498266523"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hosted_service",
        "status",
        existing_type=sa.Enum(
            "INIT",
            "VALIDATING",
            "REGISTERING",
            "PUSHING_NEW_VERSION",
            "DEPLOYING",
            "PROFILING",
            "UP",
            "DOWN",
            "ERROR",
            name="hostedservicestatus",
        ),
        type_=sa.Enum(
            "INIT",
            "VALIDATING",
            "REGISTERING",
            "PUSHING_NEW_VERSION",
            "BUILDING",
            "DEPLOYING",
            "PROFILING",
            "UP",
            "DOWN",
            "ERROR",
            name="hostedservicestatus",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE hosted_service
        SET status = 'PUSHING_NEW_VERSION'
        WHERE status = 'BUILDING';
    """)

    op.alter_column(
        "hosted_service",
        "status",
        existing_type=sa.Enum(
            "INIT",
            "VALIDATING",
            "REGISTERING",
            "PUSHING_NEW_VERSION",
            "BUILDING",
            "DEPLOYING",
            "PROFILING",
            "UP",
            "DOWN",
            "ERROR",
            name="hostedservicestatus",
        ),
        type_=sa.Enum(
            "INIT",
            "VALIDATING",
            "REGISTERING",
            "PUSHING_NEW_VERSIONDEPLOYING",
            "PROFILING",
            "UP",
            "DOWN",
            "ERROR",
            name="hostedservicestatus",
        ),
        existing_nullable=False,
    )

    # ### end Alembic commands ###
