"""haas_v2

Revision ID: b08498266523
Revises: a1ac61966c3f
Create Date: 2025-11-13 16:15:51.758557

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b08498266523"
down_revision: Union[str, None] = "a1ac61966c3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_balance",
        sa.Column("account_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("balance", sa.DECIMAL(precision=38, scale=0), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_table(
        "token_rate",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token_symbol", sa.VARCHAR(length=128), nullable=False),
        sa.Column("usd_per_token", mysql.FLOAT(), nullable=False),
        sa.Column("cogs_per_usd", sa.DECIMAL(precision=38, scale=0), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hosted_service",
        sa.Column("id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("daemon_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum("INIT", "VALIDATING", "REGISTERING", "PUSHING_NEW_VERSION", "DEPLOYING", "PROFILING", "UP", "DOWN", "ERROR", name="hostedservicestatus"),
            nullable=False,
        ),
        sa.Column("github_account_name", sa.VARCHAR(length=256), nullable=False),
        sa.Column("github_repository_name", sa.VARCHAR(length=256), nullable=False),
        sa.Column("last_commit_url", sa.VARCHAR(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["daemon_id"], ["daemon.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("daemon_id", name="uq_daemon"),
    )
    op.create_index(
        op.f("ix_hosted_service_daemon_id"), "hosted_service", ["daemon_id"], unique=False
    )

    op.drop_table("claiming_period")

    op.create_index(op.f("ix_daemon_account_id"), "daemon", ["account_id"], unique=False)

    op.execute("""
        INSERT INTO account_balance (account_id, balance)
        SELECT DISTINCT account_id, 0.00
        FROM daemon
        WHERE account_id IS NOT NULL
    """)

    op.create_foreign_key(
        None,
        "daemon",
        "account_balance",
        ["account_id"],
        ["account_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("daemon", "service_published")
    op.drop_column("daemon", "end_at")
    op.drop_column("daemon", "start_at")

    op.execute("""
        UPDATE daemon
        SET status = CASE status
            WHEN 'RESTARTING' THEN 'STARTING'
            WHEN 'READY_TO_START' THEN 'INIT'
            WHEN 'DELETING' THEN 'DOWN'
        END
        WHERE status IN ('RESTARTING', 'READY_TO_START', 'DELETING');
    """)
    op.alter_column(
        "daemon",
        "status",
        existing_type=sa.Enum(
            "INIT", "READY_TO_START", "STARTING", "RESTARTING", "DELETING", "UP", "DOWN", "ERROR"
        ),
        type_=sa.Enum("INIT", "STARTING", "UP", "DOWN", "ERROR", name="daemonstatus"),
        existing_nullable=False,
    )

    op.add_column("order", sa.Column("account_id", sa.VARCHAR(length=128), nullable=False))
    op.execute("""
    UPDATE `order` o
    SET account_id = (
        SELECT account_id
        FROM daemon d
        WHERE d.id = o.daemon_id
    )
    WHERE daemon_id IS NOT NULL;
    """)

    op.add_column("order", sa.Column("amount", sa.DECIMAL(precision=38, scale=0), nullable=False))
    op.drop_constraint("order_ibfk_1", "order", type_="foreignkey")
    op.drop_index("ix_order_daemon_id", table_name="order")
    op.create_index(op.f("ix_order_account_id"), "order", ["account_id"], unique=False)
    op.create_foreign_key(
        None,
        "order",
        "account_balance",
        ["account_id"],
        ["account_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "order",
        "status",
        existing_type=mysql.ENUM("PROCESSING", "SUCCESS", "FAILED"),
        type_=sa.Enum(
            "CREATED", "PROCESSING", "SUCCESS", "FAILED", "CANCELLED", "EXPIRED", name="orderstatus"
        ),
        existing_nullable=False,
    )
    op.drop_column("order", "daemon_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("daemon_id", mysql.VARCHAR(length=128), nullable=False))
    op.drop_constraint(None, "order", type_="foreignkey")
    op.create_foreign_key(
        "order_ibfk_1",
        "order",
        "daemon",
        ["daemon_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_order_account_id"), table_name="order")
    op.create_index("ix_order_daemon_id", "order", ["daemon_id"], unique=False)
    op.drop_column("order", "amount")
    op.drop_column("order", "account_id")

    op.execute("""
        UPDATE 'order'
        SET status = CASE status
            WHEN 'CREATED' THEN 'PROCESSING'
            WHEN 'CANCELLED' THEN 'FAILED'
            WHEN 'EXPIRED' THEN 'FAILED'
        END
        WHERE status IN ('CREATED', 'CANCELLED', 'EXPIRED');
    """)
    op.alter_column(
        "order",
        "status",
        existing_type=mysql.ENUM(
            "CREATED", "PROCESSING", "SUCCESS", "FAILED", "CANCELLED", "EXPIRED"
        ),
        type_=sa.Enum("PROCESSING", "SUCCESS", "FAILED", name="orderstatus"),
        existing_nullable=False,
    )
    op.add_column("daemon", sa.Column("start_at", mysql.TIMESTAMP(), nullable=False))
    op.add_column("daemon", sa.Column("end_at", mysql.TIMESTAMP(), nullable=False))
    op.add_column(
        "daemon",
        sa.Column(
            "service_published", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "daemon", type_="foreignkey")
    op.drop_index(op.f("ix_daemon_account_id"), table_name="daemon")
    op.create_table(
        "claiming_period",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("daemon_id", mysql.VARCHAR(length=128), nullable=False),
        sa.Column("start_at", mysql.TIMESTAMP(), nullable=False),
        sa.Column("end_at", mysql.TIMESTAMP(), nullable=False),
        sa.Column("status", mysql.ENUM("ACTIVE", "INACTIVE", "FAILED"), nullable=False),
        sa.Column(
            "created_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["daemon_id"],
            ["daemon.id"],
            name="claiming_period_ibfk_1",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_claiming_period_daemon_id", "claiming_period", ["daemon_id"], unique=False)
    op.drop_index(op.f("ix_hosted_service_daemon_id"), table_name="hosted_service")
    op.drop_table("hosted_service")
    op.drop_table("token_rate")
    op.drop_table("account_balance")
    # ### end Alembic commands ###
