"""unique_constraint_for_service_group_table

Revision ID: 057da5046949
Revises: 5ae9b3bdc7ce
Create Date: 2021-05-24 22:42:15.311655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057da5046949'
down_revision = '0cc7c0eab723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_srvc_grp', 'service_group', ['org_id', 'service_id', 'group_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_srvc_grp', 'service_group', type_='unique')
    # ### end Alembic commands ###
