"""added demoComponent flag in service metadata

Revision ID: 0cc7c0eab723
Revises: 5ae9b3bdc7ce
Create Date: 2021-05-24 13:52:35.647079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0cc7c0eab723'
down_revision = '5ae9b3bdc7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_metadata', sa.Column('demo_component_available', mysql.TINYINT(display_width=1), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_metadata', 'demo_component_available')
    # ### end Alembic commands ###
