"""changed_decimal_precision

Revision ID: 25a807e99fc4
Revises: b90651e00ea9
Create Date: 2025-05-05 21:50:55.159551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25a807e99fc4'
down_revision = 'b90651e00ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mpe_channel', 'balance_in_cogs',
               existing_type=mysql.DECIMAL(precision=19, scale=8),
               type_=sa.DECIMAL(precision=38, scale=0),
               existing_nullable=True)
    op.alter_column('mpe_channel', 'pending',
               existing_type=mysql.DECIMAL(precision=19, scale=8),
               type_=sa.DECIMAL(precision=38, scale=0),
               existing_nullable=True)
    op.alter_column('mpe_channel', 'consumed_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=38, scale=0),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mpe_channel', 'consumed_balance',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('mpe_channel', 'pending',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=mysql.DECIMAL(precision=19, scale=8),
               existing_nullable=True)
    op.alter_column('mpe_channel', 'balance_in_cogs',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=mysql.DECIMAL(precision=19, scale=8),
               existing_nullable=True)
    # ### end Alembic commands ###
