"""onupdate_timestamp

Revision ID: 5c110ac11682
Revises: e2a6a7075af0
Create Date: 2025-07-03 14:10:28.990138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c110ac11682'
down_revision = 'e2a6a7075af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tables = [
        'mpe_channel',
        'org_group',
        'organization',
        'service',
        'service_endpoint',
        'service_group',
        'service_media',
        'service_metadata',
        'service_tags',
        'offchain_service_config'
    ]

    for table in tables:
        op.alter_column(table, 'created_on',
                        existing_type = sa.TIMESTAMP(),
                        nullable = False,
                        server_default = sa.text("CURRENT_TIMESTAMP"))
        op.alter_column(table, 'updated_on',
                        existing_type = sa.TIMESTAMP(),
                        nullable = False,
                        server_default = sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tables = [
        'mpe_channel',
        'org_group',
        'organization',
        'service',
        'service_endpoint',
        'service_group',
        'service_media',
        'service_metadata'
    ]

    for table in tables:
        op.alter_column(table, 'created_on',
                        existing_type = sa.TIMESTAMP(),
                        nullable = False,
                        server_default = sa.func.now())
        op.alter_column(table, 'updated_on',
                        existing_type = sa.TIMESTAMP(),
                        nullable = False,
                        server_default = sa.func.now())
    # ### end Alembic commands ###
