"""made demoComponent in seviceMetadata non nullable

Revision ID: 5f9cf395f175
Revises: b7e01423560c
Create Date: 2021-06-02 15:15:58.705606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9cf395f175'
down_revision = 'b7e01423560c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
