"""remo_demo_component_available_column

Revision ID: 9756edf63f44
Revises: 4dd258579fce
Create Date: 2021-07-28 16:19:47.412085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9756edf63f44'
down_revision = '4dd258579fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_off', 'offchain_service_config', ['org_id', 'service_id', 'parameter_name'])
    op.drop_index('uq_offchain_const', table_name='offchain_service_config')
    op.drop_column('service_metadata', 'demo_component_available')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_metadata', sa.Column('demo_component_available', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.create_index('uq_offchain_const', 'offchain_service_config', ['org_id', 'service_id', 'parameter_name'], unique=True)
    op.drop_constraint('uq_off', 'offchain_service_config', type_='unique')
    # ### end Alembic commands ###
