"""remove_demo_column_from_servicemetadata

Revision ID: aff69d55aea7
Revises: 4dd258579fce
Create Date: 2021-07-29 13:46:02.874080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aff69d55aea7'
down_revision = '4dd258579fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_metadata', 'demo_component_available')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_metadata', sa.Column('demo_component_available', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
