"""made demoComponent in seviceMetadata non nullable

Revision ID: b7e01423560c
Revises: 057da5046949
Create Date: 2021-05-25 14:46:06.899954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7e01423560c'
down_revision = '057da5046949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_metadata', 'demo_component_available',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_metadata', 'demo_component_available',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
