"""mapping_delete_tables

Revision ID: e2a6a7075af0
Revises: 25a807e99fc4
Create Date: 2025-07-01 13:55:39.001389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2a6a7075af0'
down_revision = '25a807e99fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('MembersFK', 'members', type_ = 'foreignkey')

    op.drop_index('daemon_id_idx', table_name = 'daemon_token')
    op.drop_constraint('uq_daemon_id', 'daemon_token', type_ = 'unique')
    op.drop_index('MembersFK_idx', table_name = 'members')

    op.drop_table('cta')
    op.drop_table('members')
    op.drop_table('banner')
    op.drop_table('daemon_token')


    op.add_column('mpe_channel', sa.Column('created_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('mpe_channel', sa.Column('updated_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('mpe_channel', 'consumed_balance',
               existing_type=mysql.DECIMAL(precision=38, scale=0),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint('uq_channel', 'mpe_channel', type_='unique')
    op.create_unique_constraint('uq_channel', 'mpe_channel', ['channel_id', 'sender', 'signer', 'recipient', 'groupId'])
    op.drop_column('mpe_channel', 'row_updated')
    op.drop_column('mpe_channel', 'row_created')
    op.add_column('org_group', sa.Column('created_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('org_group', sa.Column('updated_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('org_group', 'group_id',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('org_group', 'payment',
               existing_type=mysql.JSON(),
               nullable=False)
    op.create_index(op.f('ix_org_group_org_id'), 'org_group', ['org_id'], unique=False)
    op.create_foreign_key(None, 'org_group', 'organization', ['org_id'], ['org_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('org_group', 'row_created')
    op.drop_column('org_group', 'row_updated')
    op.add_column('organization', sa.Column('created_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('organization', sa.Column('updated_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('organization', 'org_assets_url',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('organization', 'description',
               existing_type=mysql.VARCHAR(length=256),
               type_=mysql.JSON(),
               nullable=False)
    op.alter_column('organization', 'assets_hash',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('organization', 'contacts',
               existing_type=mysql.JSON(),
               nullable=False)
    op.drop_column('organization', 'row_updated')
    op.drop_column('organization', 'row_created')
    op.add_column('service', sa.Column('created_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('service', sa.Column('updated_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('service', 'hash_uri',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.create_index(op.f('ix_service_org_id'), 'service', ['org_id'], unique=False)
    op.create_foreign_key(None, 'service', 'organization', ['org_id'], ['org_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('service', 'row_updated')
    op.drop_column('service', 'row_created')
    op.add_column('service_endpoint', sa.Column('created_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('service_endpoint', sa.Column('updated_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('service_endpoint', 'is_available',
               existing_type=mysql.BIT(length=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('service_endpoint', 'failed_status_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_constraint('ServiceEndpt', 'service_endpoint', type_='foreignkey')
    op.drop_index('ServiceFK_idx', table_name='service_endpoint')
    op.create_index(op.f('ix_service_endpoint_service_row_id'), 'service_endpoint', ['service_row_id'], unique=False)
    op.create_foreign_key(None, 'service_endpoint', 'service', ['service_row_id'], ['row_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('service_endpoint', 'row_updated')
    op.drop_column('service_endpoint', 'row_created')
    op.add_column('service_group', sa.Column('created_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('service_group', sa.Column('updated_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('service_group', 'pricing',
               existing_type=mysql.JSON(),
               nullable=False)
    op.drop_constraint('ServiceGrpFK', 'service_group', type_='foreignkey')
    op.drop_index('ServiceFK_idx', table_name='service_group')
    op.create_index(op.f('ix_service_group_service_row_id'), 'service_group', ['service_row_id'], unique=False)
    op.create_foreign_key(None, 'service_group', 'service', ['service_row_id'], ['row_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('service_group', 'row_updated')
    op.drop_column('service_group', 'row_created')
    op.alter_column('service_media', 'service_row_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('service_media', 'org_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('service_media', 'service_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('service_media', 'file_type',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('service_media', 'asset_type',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('service_media', 'alt_text',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('service_media', 'hash_uri',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('service_media', 'created_on',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    op.alter_column('service_media', 'updated_on',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_service_media_service_row_id'), 'service_media', ['service_row_id'], unique=False)
    op.drop_constraint('ServiceMedisFK', 'service_media', type_='foreignkey')
    op.create_foreign_key(None, 'service_media', 'service', ['service_row_id'], ['row_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('service_metadata', sa.Column('created_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('service_metadata', sa.Column('updated_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('service_metadata', 'model_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('service_metadata', 'assets_url',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('service_metadata', 'assets_hash',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('service_metadata', 'service_rating',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('service_metadata', 'ranking',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('service_metadata', 'contributors',
               existing_type=mysql.JSON(),
               nullable=False)
    op.drop_constraint('ServiceMdataFK', 'service_metadata', type_='foreignkey')
    op.drop_index('ServiceFK_idx', table_name='service_metadata')
    op.create_index(op.f('ix_service_metadata_service_row_id'), 'service_metadata', ['service_row_id'], unique=False)
    op.create_foreign_key(None, 'service_metadata', 'service', ['service_row_id'], ['row_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('service_metadata', 'row_updated')
    op.drop_column('service_metadata', 'row_created')
    op.add_column('service_tags', sa.Column('created_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('service_tags', sa.Column('updated_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('ServiceFK', 'service_tags', type_='foreignkey')
    op.drop_index('ServiceFK_idx', table_name='service_tags')
    op.create_index(op.f('ix_service_tags_service_row_id'), 'service_tags', ['service_row_id'], unique=False)
    op.create_foreign_key(None, 'service_tags', 'service', ['service_row_id'], ['row_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('service_tags', 'row_created')
    op.drop_column('service_tags', 'row_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_tags', sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True))
    op.add_column('service_tags', sa.Column('row_created', mysql.TIMESTAMP(), nullable=True))
    op.drop_constraint(None, 'service_tags', type_='foreignkey')
    op.create_foreign_key('ServiceFK', 'service_tags', 'service', ['service_row_id'], ['row_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_service_tags_service_row_id'), table_name='service_tags')
    op.create_index('ServiceFK_idx', 'service_tags', ['service_row_id'], unique=False)
    op.drop_column('service_tags', 'updated_on')
    op.drop_column('service_tags', 'created_on')
    op.add_column('service_metadata', sa.Column('row_created', mysql.TIMESTAMP(), nullable=True))
    op.add_column('service_metadata', sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True))
    op.drop_constraint(None, 'service_metadata', type_='foreignkey')
    op.create_foreign_key('ServiceMdataFK', 'service_metadata', 'service', ['service_row_id'], ['row_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_service_metadata_service_row_id'), table_name='service_metadata')
    op.create_index('ServiceFK_idx', 'service_metadata', ['service_row_id'], unique=False)
    op.alter_column('service_metadata', 'contributors',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('service_metadata', 'ranking',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('service_metadata', 'service_rating',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('service_metadata', 'assets_hash',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('service_metadata', 'assets_url',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('service_metadata', 'model_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('service_metadata', 'updated_on')
    op.drop_column('service_metadata', 'created_on')
    op.drop_constraint(None, 'service_media', type_='foreignkey')
    op.create_foreign_key('ServiceMedisFK', 'service_media', 'service', ['service_row_id'], ['row_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_service_media_service_row_id'), table_name='service_media')
    op.alter_column('service_media', 'updated_on',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('service_media', 'created_on',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('service_media', 'hash_uri',
               existing_type=sa.VARCHAR(length=512),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('service_media', 'alt_text',
               existing_type=sa.VARCHAR(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('service_media', 'asset_type',
               existing_type=sa.VARCHAR(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('service_media', 'file_type',
               existing_type=sa.VARCHAR(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('service_media', 'service_id',
               existing_type=sa.VARCHAR(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('service_media', 'org_id',
               existing_type=sa.VARCHAR(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('service_media', 'service_row_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('service_group', sa.Column('row_created', mysql.TIMESTAMP(), nullable=True))
    op.add_column('service_group', sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True))
    op.drop_constraint(None, 'service_group', type_='foreignkey')
    op.create_foreign_key('ServiceGrpFK', 'service_group', 'service', ['service_row_id'], ['row_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_service_group_service_row_id'), table_name='service_group')
    op.create_index('ServiceFK_idx', 'service_group', ['service_row_id'], unique=False)
    op.alter_column('service_group', 'pricing',
               existing_type=mysql.JSON(),
               nullable=True)
    op.drop_column('service_group', 'updated_on')
    op.drop_column('service_group', 'created_on')
    op.add_column('service_endpoint', sa.Column('row_created', mysql.TIMESTAMP(), nullable=True))
    op.add_column('service_endpoint', sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True))
    op.drop_constraint(None, 'service_endpoint', type_='foreignkey')
    op.create_foreign_key('ServiceEndpt', 'service_endpoint', 'service', ['service_row_id'], ['row_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_service_endpoint_service_row_id'), table_name='service_endpoint')
    op.create_index('ServiceFK_idx', 'service_endpoint', ['service_row_id'], unique=False)
    op.alter_column('service_endpoint', 'failed_status_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('service_endpoint', 'is_available',
               existing_type=sa.BOOLEAN(),
               type_=mysql.BIT(length=1),
               existing_nullable=True)
    op.drop_column('service_endpoint', 'updated_on')
    op.drop_column('service_endpoint', 'created_on')
    op.add_column('service', sa.Column('row_created', mysql.TIMESTAMP(), nullable=True))
    op.add_column('service', sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True))
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_index(op.f('ix_service_org_id'), table_name='service')
    op.alter_column('service', 'hash_uri',
               existing_type=sa.VARCHAR(length=128),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('service', 'updated_on')
    op.drop_column('service', 'created_on')
    op.add_column('organization', sa.Column('row_created', mysql.TIMESTAMP(), nullable=True))
    op.add_column('organization', sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True))
    op.alter_column('organization', 'contacts',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('organization', 'assets_hash',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('organization', 'description',
               existing_type=mysql.JSON(),
               type_=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('organization', 'org_assets_url',
               existing_type=mysql.JSON(),
               nullable=True)
    op.drop_column('organization', 'updated_on')
    op.drop_column('organization', 'created_on')
    op.add_column('org_group', sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True))
    op.add_column('org_group', sa.Column('row_created', mysql.TIMESTAMP(), nullable=True))
    op.drop_constraint(None, 'org_group', type_='foreignkey')
    op.drop_index(op.f('ix_org_group_org_id'), table_name='org_group')
    op.alter_column('org_group', 'payment',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('org_group', 'group_id',
               existing_type=sa.VARCHAR(length=256),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_column('org_group', 'updated_on')
    op.drop_column('org_group', 'created_on')
    op.add_column('mpe_channel', sa.Column('row_created', mysql.TIMESTAMP(), nullable=True))
    op.add_column('mpe_channel', sa.Column('row_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_constraint('uq_channel', 'mpe_channel', type_='unique')
    op.create_unique_constraint('uq_channel', 'mpe_channel', ['channel_id', 'sender', 'recipient', 'groupId'])
    op.alter_column('mpe_channel', 'consumed_balance',
               existing_type=mysql.DECIMAL(precision=38, scale=0),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_column('mpe_channel', 'updated_on')
    op.drop_column('mpe_channel', 'created_on')
    op.create_table('cta',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('banner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('variant', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('rank', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('row_created', mysql.TIMESTAMP(), nullable=True),
    sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['banner_id'], ['banner.id'], name='cta_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('members',
    sa.Column('row_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('member', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('row_created', mysql.TIMESTAMP(), nullable=True),
    sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], name='MembersFK', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('MembersFK_idx', 'members', ['org_id'], unique=False)
    op.create_table('daemon_token',
    sa.Column('row_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('daemon_id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('token', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('expiration', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('row_created', mysql.TIMESTAMP(), nullable=True),
    sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('row_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_daemon_id', 'daemon_token', ['daemon_id'], unique=True)
    op.create_index('daemon_id_idx', 'daemon_token', ['daemon_id'], unique=False)
    op.create_table('banner',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('image_alignment', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('alt_text', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('rank', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('row_created', mysql.TIMESTAMP(), nullable=True),
    sa.Column('row_updated', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
