"""org publish nonce

Revision ID: 013efbf93251
Revises: 59be957f84ad
Create Date: 2020-05-28 21:35:10.452100

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '013efbf93251'
down_revision = '59be957f84ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_state', sa.Column('nonce', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_state', 'nonce')
    # ### end Alembic commands ###
