"""remove registration id type

Revision ID: 027993bb994b
Revises: 017993bb994b
Create Date: 2020-11-19 13:38:06.541578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '027993bb994b'
down_revision = '017993bb994b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_archive', 'registration_type')
    op.drop_column('organization_archive', 'registration_id')
    op.drop_column('organization', 'registration_type')
    op.drop_column('organization', 'registration_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('registration_id', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('organization', sa.Column('registration_type', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('organization_archive', sa.Column('registration_id', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('organization_archive', sa.Column('registration_type', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
