"""offchain_service_config_table

Revision ID: 0a49b2e55f4d
Revises: 027993bb994b
Create Date: 2021-07-16 11:54:59.852355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a49b2e55f4d'
down_revision = '027993bb994b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offchain_service_config',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_uuid', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('service_uuid', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('demo_component_required', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('created_on', mysql.TIMESTAMP(), nullable=False),
    sa.Column('updated_on', mysql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['service_uuid'], ['service.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offchain_service_config')
    # ### end Alembic commands ###
