"""add service_type

Revision ID: 3312b862c6cb
Revises: 57deaf9ab42f
Create Date: 2024-03-26 10:22:48.873379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3312b862c6cb'
down_revision = '57deaf9ab42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('service_type', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'service_type')
    # ### end Alembic commands ###
