"""comment in org state

Revision ID: 4a6610e98b11
Revises: 013efbf93251
Create Date: 2020-10-08 17:27:27.438370

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a6610e98b11'
down_revision = '013efbf93251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_state', sa.Column('comments', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_state', 'comments')
    # ### end Alembic commands ###
