"""offchain_service_config_table_added

Revision ID: 57deaf9ab42f
Revises: 027993bb994b
Create Date: 2021-07-16 15:58:49.983679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57deaf9ab42f'
down_revision = '027993bb994b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offchain_service_config',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_uuid', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('service_uuid', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('parameter_name', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('parameter_value', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('created_on', mysql.TIMESTAMP(), nullable=False),
    sa.Column('updated_on', mysql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['service_uuid'], ['service.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('org_uuid', 'service_uuid', 'parameter_name', name='uq_offchain_const')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offchain_service_config')
    # ### end Alembic commands ###
