"""addition of service comment table

Revision ID: 59be957f84ad
Revises: 3104643cd4e3
Create Date: 2020-03-20 16:56:27.129242

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59be957f84ad'
down_revision = '3104643cd4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_comment',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_uuid', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('service_uuid', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('support_type', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('user_type', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('commented_by', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('created_on', mysql.TIMESTAMP(), nullable=False),
    sa.Column('updated_on', mysql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('row_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_comment')
    # ### end Alembic commands ###
