"""storage_provider_column

Revision ID: 9fc219c82134
Revises: fed330af2aa5
Create Date: 2025-02-04 14:33:59.194536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fc219c82134'
down_revision = 'fed330af2aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('storage_provider', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'storage_provider')
    # ### end Alembic commands ###
