"""baseline

Revision ID: aa29ea1ad88f
Revises: 
Create Date: 2020-02-03 17:49:13.221311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa29ea1ad88f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('uuid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('org_type', sa.VARCHAR(length=128), nullable=True),
    sa.Column('origin', sa.VARCHAR(length=128), nullable=True),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('short_description', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('duns_no', sa.VARCHAR(length=36), nullable=True),
    sa.Column('contacts', mysql.JSON(), nullable=False),
    sa.Column('assets', mysql.JSON(), nullable=False),
    sa.Column('metadata_ipfs_hash', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('service_review_history',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_uuid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('service_uuid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('reviewed_service_data', mysql.JSON(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=64), nullable=False),
    sa.Column('reviewed_by', sa.VARCHAR(length=128), nullable=False),
    sa.Column('reviewed_on', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_on', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_on', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_table('group',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('org_uuid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('payment_address', sa.VARCHAR(length=128), nullable=False),
    sa.Column('payment_config', mysql.JSON(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['org_uuid'], ['organization.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_table('org_member',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('invite_code', sa.VARCHAR(length=128), nullable=False),
    sa.Column('org_uuid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('role', sa.VARCHAR(length=128), nullable=True),
    sa.Column('username', sa.VARCHAR(length=128), nullable=True),
    sa.Column('address', sa.VARCHAR(length=128), nullable=True),
    sa.Column('status', sa.VARCHAR(length=128), nullable=True),
    sa.Column('transaction_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('invited_on', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_on', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_on', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['org_uuid'], ['organization.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invite_code')
    )
    op.create_table('organization_address',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_uuid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('address_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('street_address', sa.VARCHAR(length=256), nullable=False),
    sa.Column('apartment', sa.VARCHAR(length=256), nullable=False),
    sa.Column('city', sa.VARCHAR(length=64), nullable=False),
    sa.Column('pincode', sa.VARCHAR(length=64), nullable=False),
    sa.Column('state', sa.VARCHAR(length=64), nullable=True),
    sa.Column('country', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_on', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_on', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['org_uuid'], ['organization.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_table('organization_state',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_uuid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('state', sa.VARCHAR(length=128), nullable=False),
    sa.Column('transaction_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('user_address', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created_on', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=128), nullable=False),
    sa.Column('updated_on', mysql.TIMESTAMP(), nullable=True),
    sa.Column('approved_by', sa.VARCHAR(length=128), nullable=True),
    sa.Column('approved_on', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['org_uuid'], ['organization.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_table('service',
    sa.Column('org_uuid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('service_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('metadata_ipfs_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('proto', mysql.JSON(), nullable=False),
    sa.Column('short_description', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('git_url', sa.VARCHAR(length=512), nullable=False),
    sa.Column('assets', mysql.JSON(), nullable=False),
    sa.Column('ratings', mysql.JSON(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.Column('contributors', mysql.JSON(), nullable=False),
    sa.Column('created_on', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_on', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['org_uuid'], ['organization.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('service_group',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_uuid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('service_uuid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('pricing', mysql.JSON(), nullable=False),
    sa.Column('endpoints', mysql.JSON(), nullable=False),
    sa.Column('created_on', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_on', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['service_uuid'], ['service.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('group_id'),
    sa.UniqueConstraint('org_uuid', 'service_uuid', 'group_id', name='uq_org_srvc_grp')
    )
    op.create_table('service_review_workflow',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_uuid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('service_uuid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('state', sa.VARCHAR(length=128), nullable=False),
    sa.Column('transaction_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=128), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=128), nullable=False),
    sa.Column('approved_by', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_on', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_on', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['service_uuid'], ['service.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('org_uuid', 'service_uuid', name='uq_org_srvc'),
    sa.UniqueConstraint('service_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_review_workflow')
    op.drop_table('service_group')
    op.drop_table('service')
    op.drop_table('organization_state')
    op.drop_table('organization_address')
    op.drop_table('org_member')
    op.drop_table('group')
    op.drop_table('service_review_history')
    op.drop_table('organization')
    # ### end Alembic commands ###
