"""add timestamps

Revision ID: bd53b0a16ac8
Revises: 9fc219c82134
Create Date: 2025-04-17 11:28:46.380202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd53b0a16ac8'
down_revision = '9fc219c82134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE org_member SET updated_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'org_member', 'updated_on',
        existing_type=mysql.TIMESTAMP(),
        server_default=sa.text('now()')
    )
    op.alter_column(
        'org_member', 'created_on',
        existing_type=mysql.TIMESTAMP(),
        server_default=sa.text('now()')
    )

    op.add_column('organization', sa.Column('created_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('organization', sa.Column('updated_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))

    op.alter_column(
        'organization_address',
        'created_on',
        existing_type=mysql.TIMESTAMP(),
        server_default=sa.text('now()')
    )
    op.alter_column(
        'organization_address',
        'updated_on',
        existing_type=mysql.TIMESTAMP(),
        server_default=sa.text('now()')
    )

    op.add_column('organization_archive', sa.Column('created_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('organization_archive', sa.Column('updated_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    
    op.execute("UPDATE organization_state SET updated_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'organization_state',
        'created_on',
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text('now()')
    )
    op.execute("UPDATE organization_state SET created_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'organization_state',
        'updated_on',
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text('now()')
    )

    op.add_column('group', sa.Column('created_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('group', sa.Column('updated_on', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    
    op.execute("UPDATE offchain_service_config SET updated_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'offchain_service_config',
        'created_on',
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text('now()')
    )
    op.execute("UPDATE offchain_service_config SET created_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'offchain_service_config',
        'updated_on',
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text('now()')
    )

    op.execute("UPDATE service SET updated_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'service',
        'created_on',
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text('now()')
    )
    op.execute("UPDATE service SET created_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'service',
        'updated_on',
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text('now()')
    )

    op.execute("UPDATE service_comment SET updated_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'service_comment',
        'created_on',
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text('now()')
    )
    op.execute("UPDATE service_comment SET created_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'service_comment',
        'updated_on',
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text('now()')
    )

    op.execute("UPDATE service_group SET updated_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'service_group',
        'created_on',
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text('now()')
    )
    op.execute("UPDATE service_group SET created_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'service_group',
        'updated_on',
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text('now()')
    )

    op.execute("UPDATE service_review_history SET updated_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'service_review_history',
        'created_on',
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text('now()')
    )
    op.execute("UPDATE service_review_history SET created_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'service_review_history',
        'updated_on',
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text('now()')
    )

    op.execute("UPDATE service_state SET updated_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'service_state',
        'created_on',
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text('now()')
    )
    op.execute("UPDATE service_state SET created_on = NOW() WHERE updated_on IS NULL")
    op.alter_column(
        'service_state',
        'updated_on',
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text('now()')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_state', 'updated_on',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('organization_state', 'created_on',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.drop_column('organization_archive', 'updated_on')
    op.drop_column('organization_archive', 'created_on')
    op.alter_column('organization_address', 'updated_on',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('organization_address', 'created_on',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.drop_column('organization', 'updated_on')
    op.drop_column('organization', 'created_on')
    op.alter_column('org_member', 'updated_on',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
