"""organization archive

Revision ID: e5a43155ad50
Revises: f568768d83a9
Create Date: 2020-02-25 11:21:52.779959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5a43155ad50'
down_revision = 'f568768d83a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_archive',
    sa.Column('uuid', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('org_id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('org_type', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('origin', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('short_description', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('duns_no', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('contacts', mysql.JSON(), nullable=False),
    sa.Column('assets', mysql.JSON(), nullable=False),
    sa.Column('metadata_ipfs_uri', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('groups', mysql.JSON(), nullable=False),
    sa.Column('org_state', mysql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_archive')
    # ### end Alembic commands ###
