"""add training_indicator

Revision ID: fc1ad8c1f8b8
Revises: 3312b862c6cb
Create Date: 2024-05-02 11:08:39.254329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1ad8c1f8b8'
down_revision = '3312b862c6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('training_indicator', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'training_indicator')
    # ### end Alembic commands ###
