"""channel_txn_hs_unique_constraint_added

Revision ID: bf358060e6dd
Revises: d35eb13038d8
Create Date: 2021-08-06 13:05:31.879898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf358060e6dd'
down_revision = 'd35eb13038d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cht_hs', 'channel_transaction_history', ['order_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cht_hs', 'channel_transaction_history', type_='unique')
    # ### end Alembic commands ###
