"""wallet_key
Revision ID: f5aefdc71fe0
Revises: bf358060e6dd
Create Date: 2025-03-27 17:55:27.409866
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5aefdc71fe0'
down_revision = 'bf358060e6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('encrypted_key', sa.VARCHAR(length=512), nullable=True))

    op.alter_column('wallet', 'row_created',
                    existing_type = sa.TIMESTAMP(),
                    nullable = False,
                    server_default=sa.text('CURRENT_TIMESTAMP'))

    op.alter_column('wallet', 'row_updated',
                    existing_type = sa.TIMESTAMP(),
                    nullable = False,
                    server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    op.alter_column('user_wallet', 'row_created',
                    existing_type = sa.TIMESTAMP(),
                    nullable = False,
                    server_default = sa.text('CURRENT_TIMESTAMP'))

    op.alter_column('user_wallet', 'row_updated',
                    existing_type = sa.TIMESTAMP(),
                    nullable = False,
                    server_default = sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    op.alter_column('create_channel_event', 'row_created',
                    existing_type = sa.TIMESTAMP(),
                    nullable = False,
                    server_default = sa.text('CURRENT_TIMESTAMP'))

    op.alter_column('create_channel_event', 'row_updated',
                    existing_type = sa.TIMESTAMP(),
                    nullable = False,
                    server_default = sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    op.alter_column('channel_transaction_history', 'row_created',
                    existing_type = sa.TIMESTAMP(),
                    nullable = False,
                    server_default = sa.text('CURRENT_TIMESTAMP'))

    op.alter_column('channel_transaction_history', 'row_updated',
                    existing_type = sa.TIMESTAMP(),
                    nullable = False,
                    server_default = sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    op.alter_column('user_wallet', 'is_default',
                    existing_type = mysql.BIT(length = 1),
                    type_ = sa.BOOLEAN(),
                    nullable = False,
                    server_default = sa.text('0'))

    op.alter_column('wallet', 'status',
                    existing_type = mysql.BIT(length = 1),
                    type_ = sa.BOOLEAN(),
                    nullable = False,
                    server_default = sa.text('1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'encrypted_key')

    op.alter_column('wallet', 'row_created',
                    existing_type = sa.TIMESTAMP(),
                    nullable = True,
                    server_default = None)

    op.alter_column('wallet', 'row_updated',
                    existing_type = sa.TIMESTAMP(),
                    nullable = True,
                    server_default = None)

    op.alter_column('user_wallet', 'row_created',
                    existing_type = sa.TIMESTAMP(),
                    nullable = True,
                    server_default = None)

    op.alter_column('user_wallet', 'row_updated',
                    existing_type = sa.TIMESTAMP(),
                    nullable = True,
                    server_default = None)

    op.alter_column('create_channel_event', 'row_created',
                    existing_type = sa.TIMESTAMP(),
                    nullable = True,
                    server_default = None)

    op.alter_column('create_channel_event', 'row_updated',
                    existing_type = sa.TIMESTAMP(),
                    nullable = True,
                    server_default = None)

    op.alter_column('channel_transaction_history', 'row_created',
                    existing_type = sa.TIMESTAMP(),
                    nullable = True,
                    server_default = None)

    op.alter_column('channel_transaction_history', 'row_updated',
                    existing_type = sa.TIMESTAMP(),
                    nullable = True,
                    server_default = None)

    op.alter_column('wallet', 'status',
                    existing_type = sa.BOOLEAN(),
                    type_ = mysql.BIT(length = 1),
                    nullable = True)

    op.alter_column('user_wallet', 'is_default',
                    existing_type = sa.BOOLEAN(),
                    type_ = mysql.BIT(length = 1),
                    nullable = True)
    # ### end Alembic commands ###