"""wallet_key

Revision ID: f5aefdc71fe0
Revises: bf358060e6dd
Create Date: 2025-03-27 17:55:27.409866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5aefdc71fe0'
down_revision = 'bf358060e6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('encrypted_key', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'encrypted_key')
    # ### end Alembic commands ###
