from deployer.constant import DaemonStorageType

NETWORKS = {
    11155111: {
        "name": "test",
        "http_provider": "https://sepolia.infura.io",
        "ws_provider": "wss://sepolia.infura.io/ws",
        "db": {
            "DB_DRIVER": "mysql+pymysql",
            "DB_HOST": "localhost",
            "DB_USER": "unittest_root",
            "DB_PASSWORD": "unittest_pwd",
            "DB_NAME": "deployer_unittest_db",
            "DB_PORT": 3306,
        },
    }
}
NETWORK_ID = 11155111
TOKEN_NAME = "FET"
STAGE = "dev"
TOKEN_DECIMALS = 18

IPFS_URL = {
    "url": "ipfs.singularitynet.io",
    "port": "80",
}
REGION_NAME = ""

HAAS_BASE_URL = ""
HAAS_LOGIN = ""
HAAS_PASSWORD = ""

HAAS_REGISTRY = ""
HAAS_REG_REPO = ""
HAAS_DAEMON_IMAGE = ""
HAAS_DAEMON_BASE_URL = "HAAS_DAEMON_BASE_URL"

HAAS_DEPLOY_DAEMON_PATH = ""
HAAS_DELETE_DAEMON_PATH = ""
HAAS_GET_DAEMON_LOGS_PATH = ""
HAAS_GET_PUBLIC_KEY_PATH = ""
HAAS_DELETE_HOSTED_SERVICE_PATH = ""
HAAS_GET_HOSTED_SERVICE_LOGS_PATH = ""
HAAS_GET_CALL_EVENTS_PATH = ""

START_DAEMON_ARN = ""
GET_ALL_ORGS_ARN = ""

DEPLOY_SERVICE_TOPIC_ARN = ""

DEFAULT_DAEMON_STORAGE_TYPE = DaemonStorageType.ETCD

TRANSACTION_TTL_IN_MINUTES = 0

JWT_EXPIRATION_IN_MINUTES = 3
GITHUB_APP_ID = "1856875"
GITHUB_PRIVATE_KEY = """
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAq+QfDUFPruNAKlIMchW5OmmScAusXhKCrr9wq4BZdjcQlOs8
prIE4gfCVDmzBa1NqUEGFFgD4Ifa8e1ucZUJsUM6LwwhT781AwJ8Cpa4XcrN2+G4
oVO652KqJW101ICElWpYSEY9FYxBxHQP6u1hd/AdVhOA61J88veCRER9aHzm/s4G
8+sf4ZIrebq0oICCdqmWh1U5sN5EmAhZ0pUetv8PrrX8hG/1z058DTlGrsTrnAPH
t8s5KzBQsBAopyGuziLLUacUu1GGoGylgtcuiezm8Owhq0CLzlertGrFxMHWRrzt
Ww0GV0eakhJ4SvKHVaN5mB7KArMAXhCTlGRyWwIDAQABAoIBAGksC//NPVcRfrom
N606M3pVDB94VP++La2EPwkAYDyfloq3oAWSmMA/5RwprarEjecIfRLHg5/HICS0
lMX0XdjS/G+66UrlACeWRpUoASiKJQjrhE9ZbtuSl+6MmVZISFcvmVKnf0qG5dqw
9OhWVDPRe/Glv1S8xOzYmiDxExZxjEb8xESC0UcwFlM3sSA4tuIvSWdlfGgrUxmp
l0U3O8ODIw2KuFFeffbgINEmHDvuhpvLfNxnfusJVoH7+hQqJQDtyD6vRrGz3V+o
Jk8znRfc7t2yHUeeynfx2FDjvsMF72t80fkZCQIXWam3nZ0cN518J5y8XVA7wgBi
6gO4rFECgYEA47w1Pcvoi2dXTDDZ8KzKIkyeSqKp0HTyrI5/wbL++OwjWyw9y2xf
JHWBitHgVC35yVP9+evujVH35RvvNryOyaFLwIemYEjfTYm1NWdCZwFjADM0UAbG
0RqLE/vLGs2WgWJvbvWrSooKsh8LuVTCEnAQNDpuAYPpqRMkFz17TXkCgYEAwTmW
o5ilXZrwtcdwMM89kRfn0NIXnjzmFshnaNsjZ5BmFDrg6AN1bj15KHWzEhD5zIh6
GCJ3v3AvmAK2cyNST8PpIkRltPU6tJz/mulbb0ZvvztNP2UbAaHqQIIiWSWnkLcm
8WhrrFG4dON06nwI/CD4DSJ4i2HDcmYoyCq9jXMCgYAxTjVEvNoLHIOlBkqZNf/J
b0cyJ4eWj0tfGrcES+myIQYCnlB+s2bh8OLsGEZ2U0HqWdn5+x+5zw5ZtzOSaT6M
3vQUqgnWfNCD7BWki0ewH3e8ullQHjd7XEDSQciWc/5q4tH3dw7v43UvXVNfe79M
2KBZfnEEuPek2HUO5wvEGQKBgFGanrIM35n+u7YpuooCnD/Q1shsUik0EwCANpwk
IHm2lEXq791MyKV8NNUPkEcLAFSPNvFGbUheets6Gg/aVQL2/FjKhiG8h8SLoa+s
6j6+gqdCxkcFzjgMR8BitVrs+i22DC5cKU0nXj2Pams1Yx4IVnpFmp9S9JY16vdO
hatdAoGBAM/rBYNwUQINpmo0v5cnWmyluzUJiHBa70lmaZMHbhma9Zr9AvZsThcw
6nZb5oDaSMT51y4kREqDEEkFm9aoPQt19UcpCUfQ+XlQb93zGq742bBDGvScDHBf
17sMb9Eg4IgeDbchnwipebJ8S6sxtl6LJ7lCGVV9Mig1wGyI14AN
-----END RSA PRIVATE KEY-----

"""

REQUEST_MAX_LIMIT = 100

CONTRACT_BASE_PATH = ""
TOKEN_JSON_FILE_NAME = ""
