from enum import Enum


class EventType(Enum):
    REGISTRY = "REGISTRY"
    MPE = "MPE"
    RFAI = "RFAI"
    TOKEN_STAKE = "TOKEN_STAKE"
    SINGULARITYNET_AIRDROP='SINGULARITYNET_AIRDROP'
    OCCAM_SNET_AIRDROP='OCCAM_SNET_AIRDROP'