"""baseline

Revision ID: 9d5f5412bc9e
Revises: 
Create Date: 2020-02-24 17:13:02.714929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d5f5412bc9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_verification',
    sa.Column('transaction_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('user_reference_id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('call_back_type', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('jumio_reference', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('verification_status', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('id_scan_status', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('id_scan_source', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('transaction_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('callback_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('identity_verification', mysql.JSON(), nullable=True),
    sa.Column('id_type', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_verification')
    # ### end Alembic commands ###
