"""duns verification

Revision ID: f1aacfcca989
Revises: 398d6252cdce
Create Date: 2020-03-18 01:22:53.321239

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1aacfcca989'
down_revision = '398d6252cdce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duns_verification',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('verification_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('org_uuid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('row_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duns_verification')
    # ### end Alembic commands ###
